# Generated by Django 5.2.13 on 2026-04-30 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_phone_user_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invited_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="invited_users", to="users.user"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
